### ISSUE TITLE
Implement advanced card properties

### ISSUE THREAD

**Issue by naniantero** [OpusCapita/oc-cm-common-layouts#9]
Implement advanced advanced card properties available in https://github.com/OpusCapita/react-cards, such as: 

- setExpanded
- expanded
- id

**Comment by havanki** [comment]
Isn't this solved with latest version ? 
#23 PR indicates that it's completed so closing this one

**Comment by naniantero** [comment]
That is very true, my friend. Didn't remember this one :)
